apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: buildnumber
      description: test
      default: defaultbuildnum
    - name: secprop
      description: test 
  steps:
  - name: task-one-step-one
    env:
      - name: SECURE_TEST
        valueFrom:
          secretKeyRef:
            name: secure-properties
            key: securetest
      - name: ENV
        valueFrom:
          configMapKeyRef:
            name: environment-properties
            key: environment
      - name: REGION
        valueFrom:
          configMapKeyRef:
            name: environment-properties
            key: region
      - name: ROLESEC
        valueFrom:
          configMapKeyRef:
            name: environment-properties
            key: vault-role-secret
      - name: BUILD_NUMBER
        value: $(params.buildnumber)
      - name: SEC_PROP
        value: $(params.secprop)
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo $SECURE_TEST && echo $SECURE_TEST-$SECURE_TEST-$SECURE_TEST && echo $ENV && echo $ENV && echo as param $SEC_PROP-$SEC_PROP-$SEC_PROP && echo $SECURE_TEST echo $REGION && echo $ROLESEC'] # tests that targetpath works
  - name: task-one-step-two
    image: ubuntu
    command: ['bash']
    envFrom:
      - secretRef:
          name: secure-properties
    args: ['-c', 'for i in {1..40}; do echo GONLOGGIN 2 && env && sleep 4; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
  - name: task-two-step-one
    image: ubuntu
    command: ["/bin/bash"]
    envFrom:
      - secretRef:
          name: secure-properties
    args: ['-c', 'for i in {1..10}; do echo GONLOGGIN 2 && env && sleep 1; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
    - name: secprop
      description: test
  tasks:
  - name: task1
    params:
      - name: buildnumber
        value: $(params.buildnumber)
      - name: secprop
        value: $(params.secprop)
    taskRef:
      name: task1
  - name: task2
    taskRef:
      name: task2
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
    - name: secprop
      description: secval
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: cutting-down-trees-run
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: 999-working-logs-long
        params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: secprop
          value: $(params.secprop)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: v0.32.0
    - name: gitrepositoryurl
      value: https://github.com/GoogleContainerTools/skaffold
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Git Triggers EventListener!
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-listener
spec:
  triggers:
    - binding:
        name: manual-pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Manual Triggers EventListener!
